#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# --- Experiment configurations --------------------------------------------------------------------

# specify time limit to be used for cross-validation
max_time: 300

# --- Data configurations --------------------------------------------------------------------------

# which data set to use
dataset: /Users/Marie-Philine/tubCloud/SWNteam/_RESEARCH/W-E_jointAnalysis/REU_Classification/Processed Data/REU2016_set2.csv

features:
- Duration
- Peak
- Volume
- Mode
- Hour
- Weekday
- Weekend


target:
- SumAs
 

# --- Validation configuration ---------------------------------------------------------------------

# specify how many folds to use for cross-validation
n-folds: 2



# --- Model configuration --------------------------------------------------------------------------

# specify one or multiple classification models (RandomForest, LightGBM, XGBoost, ANN):
algorithm:
- RandomForestClassifier
# - LGBMClassifier
# - XGBoost
# - ANN

# set hyperparameters for selected model(s)
hyperParams:
    RandomForestClassifier:
         n_estimators:
             - 100
             - 200 
         max_depth:
             - 10
             # - 30
             # - 45
             # - 75
            # - 100
         min_samples_split:
             - 2
             #- 5
            # - 50
         min_samples_leaf:
             - 1
             #- 2
             #- 4
            # - 1000
    LGBMClassifier:
        max_depth:
            - 3
            #- 4
            #- 5
        learning_rate:
            - 0.01
            #- 0.02
            #- 0.04
            #- 0.08
            #- 0.16
            #- 0.32

             
             
                  
